{% set version = "1.6.36" %}

package:
  name: libpng
  version: {{ version }}

source:
  url: http://download.sourceforge.net/libpng/libpng-{{ version }}.tar.gz
  sha256: ca13c548bde5fb6ff7117cc0bdab38808acb699c0eccb613f0e4697826e1fd7d
  patches:
    - 0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    # Tests fail on aarch64 due to some optimizations
    # https://github.com/glennrp/libpng/issues/266
    # patches were taken from debian
    # https://sources.debian.org/src/libpng1.6/1.6.36-2/debian/patches/
    - revert-1ceaa83a844cd3ecef25279d60720f910b96f297.patch
    - revert-b66ed711315c46ef6c556c83c0074ecdcbd9937f.patch
    - revert-7734cda20cf1236aef60f3bbd2267c97bbb40869.patch

build:
  number: 1000
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('libpng', max_pin='x.x') }}

requirements:
  build:
    - cmake  # [win]
    - m2-patch  # [win]
    - libtool  # [not win]
    - autoconf  # [not win]
    - automake  # [not win]
    - {{ compiler('c') }}
    - make      # [not win]
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libpng.a  # [not win]
    - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}  # [not win]
    - libpng-config --version  # [not win]

about:
  home: http://www.libpng.org/pub/png/libpng.html
  license: zlib/libpng
  license_file: LICENSE
  license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
  summary: 'PNG reference library'
  description: |
    libpng is the official PNG reference library. It supports almost all PNG
    features, is extensible, and has been extensively tested for over 20 years.
  doc_url: http://www.libpng.org/pub/png/libpng.html
  dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
    - pkgw
